print("I'm hungry")
print('He ask me "Are you hungry?"')
print('------------------------')
print("I'm good and \"I Will do my best\"")
print('/\\')
print('------------------------')
print('\ta\na\ta')